menu:
  主页: /
  存档: /archives
  链接: /链接
  关于: /about

widgets: 
- search
- category
- tag
- tagcloud

excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:
